### ISSUE TITLE
Unable to edit, duplicate, delete a payment adjuster

### ISSUE THREAD

**Issue by babau67** [pdaleramirez/super-payment-adjuster#2]
Hi,

after I create a new payment adjuster and save it, I cannot edit, duplicate, delete it anymore.

In the control panel, when viewing the list of payment adjusters, the a href URL is missing. Additionally, when selecting one, the cog actions below, including Edit, Duplicate, and Delete, are disabled.

I also notice that if I click on the icon in the settings page I get this error:
Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “super-payment-adjuster/settings”

Thanks for your help.

**Craft CMS version**
4.5.10

**Craft Commerce version**
4.3.3

**Super Payment Adjuster**
1.2

**PHP version**
8.2

**Comment by pdaleramirez** [comment]
@babau67 This has been fixed on latest release; please upgrade to version 1.3. I fixed the settings page error, but there is no setting configuration for this plugin.

**Comment by babau67** [comment]
Thank you!
Now it works perfect!
